apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-ui-plugin-test2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argo-ui-plugin-test2
  template:
    metadata:
      labels:
        app: argo-ui-plugin-test2
    spec:
      containers:
        - name: argo-ui-plugin-test2
          image: sureshmavp1/argo-ui-plugin-test2:1.0.1
          imagePullPolicy: Always
          # ports:
          #   - containerPort: 3000