apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-lb-test1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-lb-test1
  template:
    metadata:
      labels:
        app: app-lb-test1
    spec:
      containers:
        - name: app-lb-test1
          image: sureshmavp1/app-lb-test1:1.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000