apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-test2-new
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argocd-test2-new
  template:
    metadata:
      labels:
        app: argocd-test2-new
    spec:
      containers:
        - name: argocd-test2-new
          image: sureshmavp1/argocd-test2-new:1.0.1
          imagePullPolicy: Always
          # ports:
          #   - containerPort: 3000