apiVersion: apps/v1
kind: Deployment
metadata:
  name: skm-argo-ui-test1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skm-argo-ui-test1
  template:
    metadata:
      labels:
        app: skm-argo-ui-test1
    spec:
      containers:
        - name: skm-argo-ui-test1
          image: sureshmavp1/skm-argo-ui-test1:1.0.1
          imagePullPolicy: Always
          # ports:
          #   - containerPort: 3000