apiVersion: v1
kind: Service
metadata:
  name: skm-argo-ui-test1
spec:
  selector:
    app: skm-argo-ui-test1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP