apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-dev-skm1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-dev-skm1
  template:
    metadata:
      labels:
        app: app-dev-skm1
    spec:
      containers:
        - name: app-dev-skm1
          image: sureshmavp1/app-dev-skm1:1.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000