apiVersion: v1
kind: Service
metadata:
  name: argo-ui-plugin-test1
spec:
  selector:
    app: argo-ui-plugin-test1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP