apiVersion: apps/v1
kind: Deployment
metadata:
  name: lb-ui-test3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lb-ui-test3
  template:
    metadata:
      labels:
        app: lb-ui-test3
    spec:
      containers:
        - name: lb-ui-test3
          image: sureshmavp1/lb-ui-test3:1.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000