apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage-demo1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backstage-demo1
  template:
    metadata:
      labels:
        app: backstage-demo1
    spec:
      containers:
        - name: backstage-demo1
          image: sureshmavp1/backstage-demo1:1.0.1
          imagePullPolicy: Always
          # ports:
          #   - containerPort: 3000