apiVersion: v1
kind: Service
metadata:
  name: backstage-demo1
spec:
  selector:
    app: backstage-demo1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP