apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-skm-app1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argo-skm-app1
  template:
    metadata:
      labels:
        app: argo-skm-app1
    spec:
      containers:
        - name: argo-skm-app1
          image: sureshmavp1/argo-skm-app1:1.0.1
          imagePullPolicy: Always
          # ports:
          #   - containerPort: 3000