apiVersion: v1
kind: Service
metadata:
  name: app-dev1-feb20
spec:
  selector:
    app: app-dev1-feb20
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer